#define CHROOT_ROOT "/opt/debian"
#define CHROOT_USER "user"
#define MOUNT "/usr/bin/mount"
#define UMOUNT "/usr/bin/umount"
#define CHROOT "/usr/bin/chroot"
#define TMUX "/usr/bin/tmux"
#define TMUX_CONF "/media/Daten/Projekte/ROSChroot/tmux.conf"
